# Generated by Django 4.0 on 2021-12-21 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_user_email_alter_user_phone_number'),
        ('postings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posting',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.user'),
            preserve_default=False,
        ),
    ]
