# Generated by Django 4.0 on 2021-12-26 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0008_alter_follow_follower_alter_follow_following'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.UniqueConstraint(fields=('follower', 'following'), name='follower_following'),
        ),
    ]
